### ISSUE TITLE
how to finetune text2img?

### ISSUE THREAD

**Issue by Johnson-yue** [viiika/Meissonic#22]
hi, thanks your share code, I want to know how to train on my own dataset  from scratch or finetune pretrained model, thanks

**Comment by viiika** [comment]
Thanks for your attention.

Please check lines 668 to 697 in `train_meissonic.py`. The `--instance_dataset` option indicates your chosen dataset, which can be any name you define. The `--instance_data_dir` specifies the path to the dataset you plan to use, typically a `.parquet` file.

A `.parquet` file is essentially a DataFrame structure. You can create one using the following script:

```bash
# Example script
import pandas as pd

# Create DataFrame
data = {
    'index': [0, 1, 2],  # Example index
    'image_path': ['path/to/image1.jpg', 'path/to/image2.jpg', 'path/to/image3.jpg'],
    'caption': ['Caption for image 1', 'Caption for image 2', 'Caption for image 3']
}

df = pd.DataFrame(data)
df.to_parquet('your_dataset.parquet')
```

Then, your DataFrame will look like this:

| index | image_path             | caption                  |
|-------|------------------------|--------------------------|
| 0     | path/to/image1.jpg     | Caption for image 1      |
| 1     | path/to/image2.jpg     | Caption for image 2      |
| 2     | path/to/image3.jpg     | Caption for image 3      |

For more details, you can refer to `dataset_utils.py`, you may need to build your own dataset class or just use/modify the existing one.

If you have further questions, please let me know.
