### ISSUE TITLE
关于论文的中的图12 添加的rope 和 norm的位置与代码相反

### ISSUE THREAD

**Issue by Johnson-yue** [viiika/Meissonic#26]
论文中显示如下， 先加rope 再Norm的
![image](https://github.com/user-attachments/assets/428bc131-523d-4a36-9542-cfdd2df78dfb)

但是再代码实现中 使用的是diffusers.models.attention_processor的FluxAttnProcessor2_0, 
https://github.com/huggingface/diffusers/blob/8d477daed507801a50dc9f285c982b1c8051ae2d/src/diffusers/models/attention_processor.py#L1843C1-L1929C33

是先Norm 再 Rope的 q和k

**Comment by viiika** [comment]
Thank you for your insightful question. There is a mistake in our Figure 12. The correct order should be normalization first, followed by positional encoding. We will address this issue in the next version of our manuscript.
