### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by nitinmukesh** [viiika/Meissonic#5]
Thanks for sharing with us, works pretty good.

I tried the fp16 version of models and made code changes in frompretained (wherever necessary by checking the fp16 version model in https://huggingface.co/MeissonFlow/Meissonic/tree/main)
torch_dtype=torch.float16, 
variant="fp16",

But it comes with error. Anyway to use fp16 version as it will consume even less memory

**Comment by Naugustogi** [comment]
Just convert it to Safetensors and upload it to Huggingface. Its just an diffusers.

**Comment by viiika** [comment]
Apologies for the delayed response. A simple approach to using the fp16 model is to first load the fp32 model with `from_pretrained`, then convert it to fp16 using `.half()`. Afterward, you can assemble the components in the pipeline and move them to the appropriate device. Currently, directly loading the text encoder with `variant="fp16"` has some unresolved issues, which we’re working to address.

**Comment by nitinmukesh** [comment]
@viiika 

Thanks for your response. Looking forward for the fix.

**Comment by nitinmukesh** [comment]
@viiika 

Just asking as I was thinking of creating Gradio Ui for int8, is FP16 fixed.

<html>
<body>
<div class="markdown-heading" dir="auto" style="box-sizing: border-box; position: relative; color: rgb(240, 246, 252); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h4 tabindex="-1" class="heading-element" dir="auto" style="box-sizing: border-box; margin-top: var(--base-size-24); margin-bottom: var(--base-size-16); font-size: 1em; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25;">Performance Benchmarks</h4><a id="user-content-performance-benchmarks" class="anchor" aria-label="Permalink: Performance Benchmarks" href="https://github.com/viiika/Meissonic#performance-benchmarks" style="box-sizing: border-box; background-color: transparent; color: var(--fgColor-accent, var(--color-accent-fg)); text-decoration: underline; float: left; padding-right: var(--base-size-4); margin: auto; line-height: 1; position: absolute; top: 9.99785px; left: -28px; display: flex; width: 28px; height: 28px; border-radius: var(--borderRadius-medium); opacity: 0; justify-content: center; align-items: center; transform: translateY(-50%); text-underline-offset: 0.2rem;"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path d="m7.775 3.275 1.25-1.25a3.5 3.5 0 1 1 4.95 4.95l-2.5 2.5a3.5 3.5 0 0 1-4.95 0 .751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018 1.998 1.998 0 0 0 2.83 0l2.5-2.5a2.002 2.002 0 0 0-2.83-2.83l-1.25 1.25a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042Zm-4.69 9.64a1.998 1.998 0 0 0 2.83 0l1.25-1.25a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042l-1.25 1.25a3.5 3.5 0 1 1-4.95-4.95l2.5-2.5a3.5 3.5 0 0 1 4.95 0 .751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018 1.998 1.998 0 0 0-2.83 0l-2.5 2.5a1.998 1.998 0 0 0 0 2.83Z"></path></svg></a></div><markdown-accessiblity-table data-catalyst="" style="box-sizing: border-box; display: block; color: rgb(240, 246, 252); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
Precision (Steps=64, Resolution=1024x1024) | Batch Size=1 (Avg. Time) | Memory Usage
-- | -- | --
FP32 | 13.32s | 12GB
FP16 | 12.35s | 9.5GB
FP8 | 12.93s | 8.7GB

</markdown-accessiblity-table>
</body>
</html>

**Comment by viiika** [comment]
I'm sorry, but I don't fully understand your question. As of now, there are no updates regarding the fp16 issue.

**Comment by nitinmukesh** [comment]
Got it, thanks.

**Comment by viiika** [comment]
```bash
python inference_fp16.py
```

This script supports fp16 inference. Just set `torch_dtype` and do not set `variant`.
